### ISSUE TITLE
Could not Initialize GLX on Arch Linux

### ISSUE THREAD

**Issue by B404Plarrison** [morevnaproject-org/opentoonz#13]
I've been running the appimage from the terminal, and it keeps outputting the following:
```

Could not initialize GLX
/tmp/.mount_57jyek/usr/bin/launch-opentoonz.sh: line 86: 12347 Aborted                 (core dumped) ./opentoonz "$@" 
```

this might also come in handy:
lspci

```
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1566
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (rev 05)
00:01.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Kabini HDMI/DP Audio
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 156b
00:02.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 16h Processor Functions 5:1
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 16h Processor Functions 5:1
00:08.0 Encryption controller: Advanced Micro Devices, Inc. [AMD] Device 1537
00:10.0 USB controller: Advanced Micro Devices, Inc. [AMD] FCH USB XHCI Controller (rev 11)
00:11.0 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 39)
00:12.0 USB controller: Advanced Micro Devices, Inc. [AMD] FCH USB EHCI Controller (rev 39)
00:13.0 USB controller: Advanced Micro Devices, Inc. [AMD] FCH USB EHCI Controller (rev 39)
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 42)
00:14.2 Audio device: Advanced Micro Devices, Inc. [AMD] FCH Azalia Controller (rev 02)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 11)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1580
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1581
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1582
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1583
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1584
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1585
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL810xE PCI Express Fast Ethernet controller (rev 07)
02:00.0 Network controller: Broadcom Limited BCM43142 802.11b/g/n (rev 01)
```

thank you for your help

**Comment by morevnaproject** [comment]
Hello! Most probably there are some problems with your graphics driver. Please let me know which driver do you use for your AMD videocard?

**Comment by 4of92000** [comment]
I'm having the exact same problem ("Could not initialize GLX") on an Intel card (on Fedora 29 KDE).

**Comment by wofogen** [comment]
I can confirm the problem on Arch Linux, Kernel 4.14. Graphic Card Intel Q45/Q43 (i think it is a GMA X4500) module i950, driver Mesa 18.2.6-0. OT builded from source and the flatpak are working nomally, only the appimage is affected. I will roll some tests to see if i can find more clues

**Comment by 4of92000** [comment]
So should I downgrade my Mesa version until the next Morevna release?

**Comment by wofogen** [comment]
> So should I downgrade my Mesa version until the next Morevna release?

Mesa 18.0.5 is the stable driver on ubuntu so i doubt you will lose anything by downgrading, especially considering your card is relatively old. Anyway it might take a while to the next Morevna release, i dont know how fedora handles downgrade but if it inst too tricky, it might be a good idea.

**Comment by leiserfg** [comment]
I fixed that by decompressing the Appimage  to a folder and running 
```
find -iname '*libxcb-dri3*' -delete   
```
that way it will use the native libxcb-dri3

**Comment by morevnaproject** [comment]
Thank you for reporting! Will add this fix to our scripts.

**Comment by morevnaproject** [comment]
Fixed now. Here are updated packages:
- https://github.com/morevnaproject-org/opentoonz/releases/download/v1.4.0-morevna/OpenToonz-1.4.0-morevna-2020.06.14-linux64-b6177.appimage
- https://github.com/morevnaproject-org/opentoonz/releases/download/v1.4.0-morevna/OpenToonz-1.4.0-morevna-2020.06.14-linux32-b6177.appimage
