### ISSUE TITLE
Appimage does not work on Ubuntu 18.04.3 (solution provided)

### ISSUE THREAD

**Issue by edukaded** [morevnaproject-org/opentoonz#29]
The most recent version of Opentoonz morevna does not work out of the box on Ubuntu 18.04.3 LTS.

Firstly the default "opener" for the .appimage extension is diskwriter, which may be some weird bug in Ubuntu.  The solution to that is to right click, go to permissions and tick the box that says "Allow executing file as program"
Alternatively you can open a command line and do
```
chmod +x OpenToonz-1.3.0-morevna-19.02.02-linux64-ac306.appimage
```

While that permits it to run, the file will (at least on my system) immediately segfault due to missing symbols.

You have to run the app image from a command line in order to see this.
```
username@computer:~/Apps/OpenToonz$ ./OpenToonz-1.3.0-morevna-19.02.02-linux64-ac306.appimage 
update stuff
./../bin/OpenToonz_1.2: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers
```

What appears to be going on is that OpenToonz is unable to the locate libxcb-dri3 yet obviously libxcb is installed already.  https://packages.ubuntu.com/source/bionic/libxcb

I was able to fix this by preloading libxcb-dri3

```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0
```

So here are my recommendations...
For the Morevna project devs, for future releases please use Snap instead of AppImage, my experience has been that it is more portable, better maintained and seems to work a lot better for projects like this.

For everyone else, here are some instructions to get this thing running on Ubuntu, perhaps this can be added to wiki or troubleshooting guide somewhere.

Step 1. Download the current version https://morevnaproject.org/opentoonz/download/

Step 2. Press the windows key, type term and launch a terminal

Step 3. Enter these commands
```
mkdir -p ~/Apps/OpenToonz
mv ~/Downloads/OpenToonz* ~/Apps/OpenToonz/
chmod +x ~/Apps/OpenToonz/*
```
At this point OpenToonz is in a subdirectory of your home directory called Apps and now we need to make a script to launch it.

```
cd ~/Apps
touch opentoonz
chmod +x opentoonz
nano opentoonz
```

This will open a text editor called nano paste this into the window by pressing shift+ctrl+v
```
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0  nohup ~/Apps/OpenToonz/OpenToonz-1.3.0-morevna-19.02.02-linux64-ac306.appimage
```
Now press ctrl+o to save and ctrl+x to exit
That nohup line is there so once you launch the app you can close the terminal without killing opentoonz.

The final step is put your Apps directory in your path for easy launching
```
nano ~/.bashrc
```

Scroll down and paste this as the final line in you .bashrc file
```
export PATH=$PATH:$HOME/Apps
```
Then hit ctrl+o to save and ctrl+x to exit.

Final step on the command line is to refresh your path.
```
source ~/.bashrc
```

Now the file will be available any time you open a terminal just execute 
```
opentoonz
```

**Comment by morevnaproject** [comment]
Fixed now. Here are updated packages:
- https://github.com/morevnaproject-org/opentoonz/releases/download/v1.4.0-morevna/OpenToonz-1.4.0-morevna-2020.06.14-linux64-b6177.appimage
- https://github.com/morevnaproject-org/opentoonz/releases/download/v1.4.0-morevna/OpenToonz-1.4.0-morevna-2020.06.14-linux32-b6177.appimage
