### ISSUE TITLE
AppImage segfaults on Ubuntu Studio

### ISSUE THREAD

**Issue by edsonmedina** [morevnaproject-org/opentoonz#39]
### Issue Summary
The AppImage dies imediately after showing the splash screen.

### Steps to Reproduce
* Download AppImage
* Give it execution permissions
* Run it

### Expected Results
The app should start normally

### Actual Results
It dies.
If I execute it from the cli I get:
```
./OpenToonz-1.4.0-morevna-2020.03.03-linux64-b6177.AppImage 
update stuff
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
plugin search directory:/home/edson/.config/OpenToonz/stuff/plugins
walkDirectory_: /home/edson/.config/OpenToonz/stuff/plugins
===== PluginLoadController::finished() =====
Segmentation fault (core dumped)
```

### System Information
* **OpenToonz Version**:  1.4.0-morevna
* **Operating System**:  Ubuntu Studio 20.4
* **CPU**: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
* **Memory**: 16Gb
* **Graphics Card**: UHD Graphics 620

**Comment by jmtscaff** [comment]
I'm having the same issue.
**OS:** Ubuntu 20.04 LTS x86_64
**CPU:** Intel i9-9900K (16) @ 5.000GHz 
**GPU:** AMD ATI Radeon RX Vega 56/64 
**Memory:** 64GB

**Comment by morevnaproject** [comment]
Thank you for reporting. Found solution, will ship new packages soon.

**Comment by morevnaproject** [comment]
Fixed now. Here are updated packages:
- https://github.com/morevnaproject-org/opentoonz/releases/download/v1.4.0-morevna/OpenToonz-1.4.0-morevna-2020.06.14-linux64-b6177.appimage
- https://github.com/morevnaproject-org/opentoonz/releases/download/v1.4.0-morevna/OpenToonz-1.4.0-morevna-2020.06.14-linux32-b6177.appimage

**Comment by jmtscaff** [comment]
Thanks working for me :)
